### ISSUE TITLE
Issue with deploying a WP instance with this theme via Kubernetes/Docker on acdh-cluster

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/fundament_wp#2]
When deploying a WP instance with this theme via Kubernetes/Docker on the cluster infrastructure, you get issues on the browser console that some assets (mostly .js and .css) are not found (404), which critically affects the usage of the customizer on WP. This happens because the assets for the custom customizer-options (in folder inc/customizer controls) are trying to be loaded from a path starting with the /bitnami/wordpress which is not exposed beyond the cloud layer.

I think this issue can be solved by changing the variables for Kirki::$url and/ord Kirki::$path in this file: https://github.com/acdh-oeaw/fundament_wp/blob/master/inc/customizer-controls/customizer-controls.php - `dirname( __FILE__ )` seems to be problematic in this type of deployment.

However I don't have a tested solution for this since I don't have the time at the moment. If it becomes necessary to use the cloud cluster for these websites in the future, someone can revisit this issue.

**Comment by dpancic** [comment]
For solving this issue, the project named Fundament is created in acdh cluster with the database fundament-wp-cluster-test on helios and the domain fundament-wp.acdh-dev.oeaw.ac.at on acdh proxy. Wordpress can be installed by following https://redmine.acdh.oeaw.ac.at/projects/dsie/wiki/Wordpress_und_Drupal
