### ISSUE TITLE
Undefined variable $term_rss_link

### ISSUE THREAD

**Issue by linxOD** [acdh-oeaw/fundament_wp#3]
Warning: Undefined variable $term_rss_link in /home/.sites/98/site9421866/web/wp-content/themes/fundament_wp-master/archive.php on line 32

This warning occurs when creating a category navbar link that summarizes all posts in one page as overview. I could not find any problems that occur with this warning but the warning is written on top of the page.

PHP Version 8
Wordpress Version 5.8.2

**Comment by nczirjak-acdh** [comment]
fixed
